CSC207-UofT/course-project-csc207_stackoverflowers

- main/ControllersPresenters/GameManager.java
- main/UseCases/GameMaker.java
> Finished the serialization and deserialization of the code.

- main/ControllersPresenters/GameManager.java
- main/Entities/GamePrompts.java
- main/Entities/Project.java
- main/UseCases/GameGenerators.java
- main/UseCases/GameMaker.java
- main/UseCases/HRSystem.java
Created new usecase class GameGenerators for game (generate intern, generate project and generate final project), also updated the projects to currentHRSystem, deleted the some methods in GameMaker and moved them to GameGenerators and redid the project generators. Refactored InternInfoList method, added new prompts to GamePrompts. Changed parameter type of updateFinalProject in HRSystem. Initialized GameGenerators in GameManager and updated some methods in the constructor.
> GameGenerator, HRSystem, GameMaker, GameManager 

- main/Entities/HiredIntern.java
- main/Entities/Intern.java
- main/Entities/InterviewIntern.java
- main/UseCases/GameGenerators.java
- main/UseCases/HRSystem.java
- test/UseCases/GameGeneratorsTest.java
Reverts CSC207-UofT/course-project-csc207_stackoverflowers#40
> Reverting till camille's is gone.

- main/UseCases/ResponseTreeMaker.java
Reverting till camille's is gone
> Revert "finished generateInternResponses and helper methods in ResponseTreeMaker"

- main/UseCases/ResponseTree.java
- main/treeConvoTextFiles/answers.txt
- main/treeConvoTextFiles/questions.txt
Reverts CSC207-UofT/course-project-csc207_stackoverflowers#33
> Revert "Camille"

- main/ControllersPresenters/ReportLevel.java
- main/Entities/Exceptions.java
- main/Entities/GamePrompts.java
- main/UseCases/FinalReportMaker.java
- main/UseCases/HRSystem.java
- main/UseCases/MonthReportMaker.java
- main/UseCases/ProjectReportMaker.java
- main/UseCases/ReportMaker.java
- test/GameMakerTest.java
things that were lost. I think
> Modifying things for tests?

- Phase1/Specification.md
Modified specification for start of the game and month-related descriptions.
> Modified specification

- main/ControllersPresenters/InterviewLevel.java
- main/Entities/GamePrompts.java
- main/SPhase.java
- main/UseCases/GameGenerators.java
- main/UseCases/GameMaker.java
- main/UseCases/HRSystem.java
- main/UseCases/InterviewMaker.java
- test/GameMakerTest.java
- test/InterviewLevelTest.java
- test/InterviewMakerTest.java
- test/UseCases/HRSystemTest.java
Kind of sorted out HRSystem. Left notes for InterviewLevel, InterviewMaker.
> Fixed errors in tests, fixed things and notes trying to solve SPhase.

- main/ControllersPresenters/GameManager.java
- main/ControllersPresenters/InterviewLevel.java
- main/Entities/Exceptions.java
- main/Entities/HiredIntern.java
- main/Entities/Intern.java
- main/Entities/InterviewIntern.java
- main/Entities/Project.java
- main/SPhase.java
- main/UseCases/FinalReportMaker.java
- main/UseCases/GameGenerators.java
- main/UseCases/GameMaker.java
- main/UseCases/HRSystem.java
- main/UseCases/MonthMaker.java
- main/UseCases/MonthReportMaker.java
- main/UseCases/ProjectReportMaker.java
- test/GameMakerTest.java
Made Entities Serializable, refactored and renamed some methods, deleted unused methods in HRSystem(only the ones that I were sure about).
Also fixed GameGenerator generating interns to save to the current HRSystem instead of a new HRSystem.
> Refactoring to make SPhase run.

- main/ControllersPresenters/Level.java
- main/ControllersPresenters/MonthLevel.java
- main/ControllersPresenters/ReportLevel.java
- main/Entities/Exceptions.java
- main/Entities/GamePrompts.java
- main/Entities/HiredIntern.java
- main/Entities/Intern.java
- main/Entities/InterviewIntern.java
- main/UseCases/FinalReportMaker.java
- main/UseCases/GameMaker.java
- main/UseCases/HRSystem.java
- main/UseCases/MonthReportMaker.java
- main/UseCases/ProjectReportMaker.java
- main/UseCases/ReportMaker.java
- test/MonthLevelTest.java
- test/MonthMakerTest.java
- test/ReportLevelTest.java
Finished methods in HRSystem that are related to Month and Report.
Used TODOs to tag unused methods that could be deleted.
Tested so that MonthLevelTest now passes.
> Finished some methods in HRSystem

- course-project-csc207_stackoverflowers.iml
- main/ControllersPresenters/GameManager.java
- main/ControllersPresenters/InterviewLevel.java
- main/ControllersPresenters/Level.java
- main/ControllersPresenters/MonthLevel.java
- main/Entities/GamePrompts.java
- main/Entities/HiredIntern.java
- main/Entities/Intern.java
- main/Entities/InterviewIntern.java
- main/SPhase.java
- main/UseCases/HRSystem.java
- main/UseCases/MonthMaker.java
- test/MonthMakerTest.java
Made changes so that Month can be playable after interviewLevel has ended. Also modified some GamePrompts to make instructions more readable to the player.
> Connecting Month to the end of InterviewLevel

- course-project-csc207_stackoverflowers.iml
- main/UseCases/GameMaker.java
- Moved all saved files to a Save folder
- Now code has the ability to not overwrite but instead save different files for same names.
> Fixing save

- Phase2/Accessibility.md
Finished accessibility document.
> Finishing Accessibility.md

- main/ControllersPresenters/GameManager.java
- main/ControllersPresenters/MonthLevel.java
- main/ControllersPresenters/ReportLevel.java
also changed GameManager so that now there are 10 interns generated.
> Fixed issue about monthLevel and reportLevel input

- main/ControllersPresenters/GameManager.java
- main/ControllersPresenters/MonthLevel.java
- main/ControllersPresenters/ReportLevel.java
- main/Entities/GamePrompts.java
- main/UseCases/GameMaker.java
- test/GameMakerTest.java
- fixed so that the saved game actually saves the progress instead of saving to either the credits or the very start.
> Fixing saved and loaded game

- main/ControllersPresenters/GameManager.java
- main/Entities/GamePrompts.java
- main/UseCases/MonthReportMaker.java
- main/UseCases/PMSystem.java
- main/UseCases/ProjectReportMaker.java
- addressed issue #119 , null pointer, and also tidied things up for monthReportMaker and projectReportMaker
> ReportLevel Issues and more

- main/ControllersPresenters/ReportLevel.java
- main/Entities/GamePrompts.java
- main/Entities/HiredIntern.java
- main/SPhase.java
- main/UseCases/MonthReportMaker.java
- test/HiredInternTest.java
made it so that the intern's skill really is upgraded.
> Upgrade skills

- main/ControllersPresenters/ReportLevel.java
- main/UseCases/FinalReportMaker.java
- main/UseCases/MonthReportMaker.java
- main/UseCases/ProjectReportMaker.java
- main/UseCases/ReportMakerFinal.java
- test/MonthReportMakerTest.java
- test/ReportLevelTest.java
Changed final report maker so that it only displays one project for final month.
> Jacob final report maker fix

- main/ControllersPresenters/GameManager.java
- main/Entities/Exceptions.java
- main/UseCases/PMSystem.java
- test/GameMakerTest.java
- test/GameManagerTest.java
- test/InterviewLevelTest.java
- test/InterviewMakerTest.java
- test/MonthLevelTest.java
- test/MonthMakerTest.java
- test/UseCases/HRSystemTest.java
making minor changes so that tests are up to date and pass. Still have some classes left but some classes pass for sure now.
> Passing Tests

- main/ControllersPresenters/InterviewLevel.java
- main/Entities/Exceptions.java
- main/UseCases/HRSystem.java
- main/UseCases/InterviewMaker.java
- test/InterviewLevelTest.java
- test/InterviewMakerTest.java
- made modifications so that now all tests pass
- also refactored for some methods to be public/private
- also added a few more tests to boost test coverage
> InterviewLevel and InterviewMaker tests
